apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: app-config
          configMap:
            name: environment.properties
            items:
              - key: eshop.properties
                path: application.properties
      containers:
        - name: app
          image: localhost:32000/eshop:{{ .Chart.Version }}
          ports:
              - containerPort: 8090
          volumeMounts:
            - name: app-config
              mountPath: /home/app/application.properties
              subPath: application.properties